version: '1'
services:
  rustshop:
    container_name: rustshop
    build:
      context: ./shop
    ports:
      - 8000:8000
    environment:
      - ROCKET_ADDRESS=0.0.0.0
      - DATABASE_URL=postgres://postgres:password@database:5432/shop
    command: /bin/sh -c "cargo run"
    volumes:
      - ./shop:/app


  frontend:
    container_name: frontendflask
    build:
      context: ./frontendFlask
    ports:
      - "5000:5050"
    environment:
      - API_SERVER_URL=http://rustshop:8000

  db:
    image: postgres:15
    container_name: database
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_DB: shop
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data